-- Active: 1743080815125@@127.0.0.1@5432@hopital
drop table prescription;
drop table patient_rdv_historique;
drop table rdv;
drop table patient;
drop table medecin;
drop table hopital;
drop table specialisation;
drop table medicament;
drop table personne;
drop table adresse;
drop table assurance;
drop type type_sexe;
drop type type_medicament;
drop type type_motif_rdv;
drop type type_specialisation;

DROP TABLE temp_patient;
DROP TABLE temp_medecin;
DROP TABLE temp_rdv;
DROP TABLE temp_medicament;
DROP TABLE temp_prescription;